export type Variables =
  | "AZURE_CLIENT_ID"
  | "AZURE_CLIENT_SECRET"
  | "AZURE_TENANT_ID"
  | "SPARK_AZURE_KEY_VAULT_NAME"
  | "SPARK_DRY_RUN"
  | "SPARK_TWITTER_CONSUMER_KEY"
  | "SPARK_TWITTER_CONSUMER_SECRET"
  | "SPARK_TWITTER_ACCESS_TOKEN"
  | "SPARK_TWITTER_ACCESS_TOKEN_SECRET";
